set search_path to medical;

--medical_card
    --medical_card marking
        --client_status: M-monitoring, R-released
        --med_status: H-healthy, U-unhealthy

insert into medical_card (id, client_status, med_status, registry_dt, comment) values (1, 'M', 'U', '2022-05-29', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (2, 'M', 'H', '2022-08-13', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (3, 'R', 'U', '2022-07-11', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (4, 'M', 'U', '2022-03-22', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (5, 'M', 'U', '2022-07-11', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (6, 'M', 'H', '2022-01-25', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (7, 'M', 'H', '2022-07-24', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (8, 'R', 'H', '2022-04-18', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (9, 'R', 'H', '2022-05-30', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (10, 'M', 'H', '2021-12-26', 'Aenean sit amet justo. Morbi ut odio.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (11, 'R', 'H', '2021-10-30', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (12, 'R', 'H', '2022-08-21', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (13, 'M', 'U', '2022-10-11', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (14, 'R', 'U', '2022-08-14', 'Vestibulum sed magna at nunc commodo placerat.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (15, 'M', 'U', '2022-09-08', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (16, 'M', 'H', '2022-10-05', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (17, 'R', 'U', '2021-12-12', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (18, 'M', 'H', '2022-09-17', 'Vestibulum sed magna at nunc commodo placerat.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (19, 'M', 'U', '2022-06-08', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (20, 'M', 'H', '2021-12-16', 'Pellentesque viverra pede ac diam.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (21, 'M', 'H', '2022-08-14', 'In eleifend quam a odio.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (22, 'R', 'U', '2021-11-19', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (23, 'R', 'U', '2022-05-02', 'Suspendisse accumsan tortor quis turpis.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (24, 'R', 'U', '2022-03-24', 'Integer tincidunt ante vel ipsum.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (25, 'M', 'H', '2022-02-11', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (26, 'M', 'H', '2022-03-31', 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (27, 'R', 'U', '2022-06-10', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (28, 'M', 'H', '2022-02-13', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (29, 'M', 'U', '2022-07-16', 'In hac habitasse platea dictumst.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (30, 'M', 'H', '2022-06-05', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (31, 'M', 'U', '2022-01-30', 'Maecenas pulvinar lobortis est.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (32, 'M', 'H', '2022-06-25', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (33, 'M', 'H', '2022-04-19', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (34, 'M', 'H', '2022-01-12', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (35, 'M', 'U', '2022-03-28', 'Aenean sit amet justo. Morbi ut odio.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (36, 'M', 'U', '2022-07-27', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (37, 'R', 'H', '2022-08-23', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (38, 'M', 'U', '2022-05-20', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (39, 'M', 'U', '2021-11-26', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (40, 'R', 'U', '2022-03-08', 'Nam tristique tortor eu pede.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (41, 'R', 'H', '2022-03-16', 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (42, 'M', 'H', '2022-04-28', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (43, 'R', 'H', '2021-11-12', 'Morbi ut odio.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (44, 'R', 'H', '2021-11-16', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (45, 'R', 'U', '2022-06-02', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (46, 'R', 'U', '2022-03-03', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (47, 'R', 'U', '2022-02-14', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (48, 'R', 'H', '2022-06-15', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (49, 'M', 'H', '2022-05-18', 'Phasellus sit amet erat. Nulla tempus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (50, 'M', 'H', '2022-01-08', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (51, 'M', 'H', '2022-09-13', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (52, 'R', 'U', '2021-12-01', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (53, 'R', 'H', '2022-03-15', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (54, 'M', 'H', '2021-12-03', 'Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (55, 'M', 'U', '2022-04-15', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (56, 'R', 'H', '2022-08-16', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (57, 'M', 'H', '2022-05-22', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (58, 'M', 'H', '2021-11-27', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (59, 'R', 'H', '2022-06-10', 'Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (60, 'M', 'H', '2022-07-17', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (61, 'M', 'U', '2021-12-16', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (62, 'R', 'H', '2022-05-27', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (63, 'M', 'H', '2022-08-22', 'Etiam faucibus cursus urna. Ut tellus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (64, 'R', 'U', '2022-02-23', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (65, 'R', 'H', '2022-08-09', 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (66, 'M', 'U', '2022-08-22', 'In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (67, 'R', 'H', '2022-03-09', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (68, 'R', 'H', '2022-05-21', 'Aliquam erat volutpat.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (69, 'M', 'H', '2022-09-24', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (70, 'R', 'U', '2022-04-09', 'Morbi a ipsum. Integer a nibh. In quis justo.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (71, 'R', 'H', '2021-12-23', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (72, 'R', 'U', '2022-10-01', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (73, 'R', 'H', '2022-03-02', 'Fusce consequat. Nulla nisl.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (74, 'R', 'U', '2022-07-27', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (75, 'R', 'H', '2022-06-06', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (76, 'R', 'U', '2022-07-02', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (77, 'M', 'U', '2022-02-22', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (78, 'R', 'H', '2022-04-28', 'Vestibulum sed magna at nunc commodo placerat.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (79, 'R', 'H', '2022-10-22', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (80, 'R', 'H', '2022-03-13', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (81, 'M', 'U', '2022-08-26', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (82, 'M', 'H', '2022-09-30', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (83, 'M', 'H', '2022-09-08', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (84, 'R', 'U', '2022-04-28', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (85, 'R', 'U', '2022-07-16', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (86, 'R', 'U', '2022-01-25', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (87, 'R', 'H', '2022-10-15', 'Nam dui.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (88, 'M', 'U', '2022-04-22', 'Integer ac neque. Duis bibendum.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (89, 'M', 'U', '2022-03-04', 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (90, 'M', 'U', '2022-07-21', 'In sagittis dui vel nisl. Duis ac nibh.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (91, 'M', 'U', '2022-10-20', 'Curabitur in libero ut massa volutpat convallis.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (92, 'M', 'U', '2021-12-03', 'Aliquam non mauris. Morbi non lectus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (93, 'R', 'H', '2022-02-19', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (94, 'M', 'H', '2022-06-09', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (95, 'M', 'U', '2022-03-14', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (96, 'M', 'U', '2022-10-17', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (97, 'M', 'U', '2022-05-02', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (98, 'M', 'U', '2022-02-03', 'Donec ut dolor.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (99, 'R', 'H', '2022-09-06', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
insert into medical_card (id, client_status, med_status, registry_dt, comment) values (100, 'M', 'H', '2021-12-22', 'Fusce consequat. Nulla nisl.');

--contact

insert into contact (id, phone_number, email, profile_link) values (1, '178-185-0356', 'rmead0@nhs.uk', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into contact (id, phone_number, email, profile_link) values (2, '650-761-0997', 'kraison1@harvard.edu', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.');
insert into contact (id, phone_number, email, profile_link) values (3, '850-724-0339', 'gblum2@tamu.edu', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
insert into contact (id, phone_number, email, profile_link) values (4, '352-235-6562', 'ecorston3@alexa.com', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into contact (id, phone_number, email, profile_link) values (5, '518-131-9127', 'ikem4@list-manage.com', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into contact (id, phone_number, email, profile_link) values (6, '665-611-8777', 'ayuryshev5@qq.com', 'Suspendisse ornare consequat lectus.');
insert into contact (id, phone_number, email, profile_link) values (7, '862-363-2020', 'mhaining6@oakley.com', 'Phasellus in felis. Donec semper sapien a libero.');
insert into contact (id, phone_number, email, profile_link) values (8, '412-823-6030', 'nfarnell7@unc.edu', 'Nunc nisl.');
insert into contact (id, phone_number, email, profile_link) values (9, '959-560-3729', 'ktodarini8@sakura.ne.jp', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into contact (id, phone_number, email, profile_link) values (10, '200-660-6791', 'rbrownhall9@nasa.gov', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into contact (id, phone_number, email, profile_link) values (11, '818-641-4184', 'aspaingowera@mediafire.com', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into contact (id, phone_number, email, profile_link) values (12, '752-276-9042', 'bbavesterb@wsj.com', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into contact (id, phone_number, email, profile_link) values (13, '861-806-6166', 'rcorsonc@creativecommons.org', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.');
insert into contact (id, phone_number, email, profile_link) values (14, '591-924-8410', 'gstreatherd@nhs.uk', 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into contact (id, phone_number, email, profile_link) values (15, '453-692-1794', 'ablundone@fc2.com', 'Morbi non quam nec dui luctus rutrum.');
insert into contact (id, phone_number, email, profile_link) values (16, '871-621-7267', 'sclewlowf@toplist.cz', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
insert into contact (id, phone_number, email, profile_link) values (17, '962-363-4565', 'dknowltong@tripod.com', 'Vestibulum sed magna at nunc commodo placerat.');
insert into contact (id, phone_number, email, profile_link) values (18, '502-232-4563', 'apendallh@webs.com', 'Aenean sit amet justo. Morbi ut odio.');
insert into contact (id, phone_number, email, profile_link) values (19, '481-201-8326', 'vdurnalli@salon.com', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into contact (id, phone_number, email, profile_link) values (20, '111-605-9085', 'schristaeasj@merriam-webster.com', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into contact (id, phone_number, email, profile_link) values (21, '586-356-1801', 'tlappinek@tuttocitta.it', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into contact (id, phone_number, email, profile_link) values (22, '692-736-7965', 'tmapstonl@meetup.com', 'Vivamus vestibulum sagittis sapien.');
insert into contact (id, phone_number, email, profile_link) values (23, '602-642-3125', 'rcollinghamm@cyberchimps.com', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into contact (id, phone_number, email, profile_link) values (24, '592-620-4697', 'okingslandn@lycos.com', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into contact (id, phone_number, email, profile_link) values (25, '300-347-5792', 'cperazzoo@gov.uk', 'Phasellus in felis. Donec semper sapien a libero.');
insert into contact (id, phone_number, email, profile_link) values (26, '193-636-7848', 'dcardozop@gmpg.org', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into contact (id, phone_number, email, profile_link) values (27, '233-252-2878', 'astanburyq@craigslist.org', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into contact (id, phone_number, email, profile_link) values (28, '205-168-1205', 'lpaolozzir@mozilla.com', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into contact (id, phone_number, email, profile_link) values (29, '267-684-3773', 'emacdermots@chicagotribune.com', 'Quisque ut erat.');
insert into contact (id, phone_number, email, profile_link) values (30, '236-298-0536', 'lrosewellt@fotki.com', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into contact (id, phone_number, email, profile_link) values (31, '895-315-2995', 'rculbardu@usnews.com', 'Fusce posuere felis sed lacus.');
insert into contact (id, phone_number, email, profile_link) values (32, '437-975-4908', 'bpurtonv@huffingtonpost.com', 'Pellentesque ultrices mattis odio.');
insert into contact (id, phone_number, email, profile_link) values (33, '184-410-2875', 'hrysonw@digg.com', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into contact (id, phone_number, email, profile_link) values (34, '684-602-8484', 'sguielx@phpbb.com', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into contact (id, phone_number, email, profile_link) values (35, '389-956-1340', 'gdalmony@networkadvertising.org', 'Fusce posuere felis sed lacus.');
insert into contact (id, phone_number, email, profile_link) values (36, '606-863-7649', 'cpearsz@jimdo.com', 'In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into contact (id, phone_number, email, profile_link) values (37, '264-880-8274', 'dberk10@yahoo.co.jp', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into contact (id, phone_number, email, profile_link) values (38, '764-798-3967', 'alissenden11@cpanel.net', 'Aliquam erat volutpat. In congue. Etiam justo.');
insert into contact (id, phone_number, email, profile_link) values (39, '610-232-2469', 'dniland12@umich.edu', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into contact (id, phone_number, email, profile_link) values (40, '765-745-0927', 'cocuolahan13@webnode.com', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into contact (id, phone_number, email, profile_link) values (41, '966-969-6179', 'mfellos14@deviantart.com', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into contact (id, phone_number, email, profile_link) values (42, '449-136-2116', 'cnayshe15@devhub.com', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into contact (id, phone_number, email, profile_link) values (43, '954-712-9370', 'btwelve16@google.it', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
insert into contact (id, phone_number, email, profile_link) values (44, '120-286-2946', 'klambdean17@dedecms.com', 'Integer non velit.');
insert into contact (id, phone_number, email, profile_link) values (45, '778-111-2078', 'elatham18@technorati.com', 'Duis mattis egestas metus. Aenean fermentum.');
insert into contact (id, phone_number, email, profile_link) values (46, '746-720-2370', 'lderbyshire19@va.gov', 'Duis ac nibh.');
insert into contact (id, phone_number, email, profile_link) values (47, '740-883-5468', 'sputterill1a@wikimedia.org', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into contact (id, phone_number, email, profile_link) values (48, '776-137-3673', 'ayarnold1b@cnet.com', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into contact (id, phone_number, email, profile_link) values (49, '588-132-1060', 'imorillas1c@hhs.gov', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into contact (id, phone_number, email, profile_link) values (50, '705-293-7140', 'dhildred1d@homestead.com', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into contact (id, phone_number, email, profile_link) values (51, '782-159-2018', 'wfishley1e@blog.com', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into contact (id, phone_number, email, profile_link) values (52, '642-883-6592', 'jandreuzzi1f@thetimes.co.uk', 'Mauris lacinia sapien quis libero.');
insert into contact (id, phone_number, email, profile_link) values (53, '867-154-1372', 'lgellert1g@cpanel.net', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into contact (id, phone_number, email, profile_link) values (54, '356-939-1927', 'cgarbert1h@businessweek.com', 'Aliquam erat volutpat. In congue.');
insert into contact (id, phone_number, email, profile_link) values (55, '941-528-0098', 'kbly1i@yale.edu', 'Donec quis orci eget orci vehicula condimentum.');
insert into contact (id, phone_number, email, profile_link) values (56, '678-465-1517', 'cmeneyer1j@imgur.com', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into contact (id, phone_number, email, profile_link) values (57, '212-510-7609', 'tmerriton1k@wisc.edu', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');
insert into contact (id, phone_number, email, profile_link) values (58, '835-722-1811', 'agribble1l@ebay.co.uk', 'Integer ac leo.');
insert into contact (id, phone_number, email, profile_link) values (59, '829-369-4772', 'brounsefull1m@biglobe.ne.jp', 'Suspendisse potenti. In eleifend quam a odio.');
insert into contact (id, phone_number, email, profile_link) values (60, '207-323-5846', 'tnijssen1n@ox.ac.uk', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into contact (id, phone_number, email, profile_link) values (61, '460-658-9258', 'bnaisey1o@nature.com', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.');
insert into contact (id, phone_number, email, profile_link) values (62, '716-885-5477', 'pguidelli1p@rambler.ru', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into contact (id, phone_number, email, profile_link) values (63, '594-130-7272', 'wfilewood1q@blog.com', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.');
insert into contact (id, phone_number, email, profile_link) values (64, '616-192-3407', 'ecruce1r@pagesperso-orange.fr', 'Aliquam non mauris.');
insert into contact (id, phone_number, email, profile_link) values (65, '180-974-9959', 'kpedican1s@comcast.net', 'Nullam molestie nibh in lectus.');
insert into contact (id, phone_number, email, profile_link) values (66, '275-560-7183', 'lelwell1t@alibaba.com', 'Vivamus vestibulum sagittis sapien.');
insert into contact (id, phone_number, email, profile_link) values (67, '784-856-9686', 'dlauthian1u@privacy.gov.au', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into contact (id, phone_number, email, profile_link) values (68, '630-295-5995', 'zsiddens1v@addthis.com', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.');
insert into contact (id, phone_number, email, profile_link) values (69, '978-854-9630', 'tratazzi1w@cloudflare.com', 'Fusce consequat. Nulla nisl. Nunc nisl.');
insert into contact (id, phone_number, email, profile_link) values (70, '512-325-8087', 'asprulls1x@mashable.com', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into contact (id, phone_number, email, profile_link) values (71, '322-184-0376', 'rcarragher1y@wordpress.org', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into contact (id, phone_number, email, profile_link) values (72, '894-364-3741', 'icorrado1z@reuters.com', 'Nulla tellus.');
insert into contact (id, phone_number, email, profile_link) values (73, '717-724-7024', 'llafflin20@t-online.de', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into contact (id, phone_number, email, profile_link) values (74, '920-894-7010', 'hcapner21@imdb.com', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into contact (id, phone_number, email, profile_link) values (75, '589-543-4330', 'mhackin22@hibu.com', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into contact (id, phone_number, email, profile_link) values (76, '713-978-6657', 'ctapply23@ucoz.ru', 'Aenean auctor gravida sem.');
insert into contact (id, phone_number, email, profile_link) values (77, '983-838-5797', 'hstartin24@behance.net', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
insert into contact (id, phone_number, email, profile_link) values (78, '584-510-4765', 'cautin25@freewebs.com', 'In congue. Etiam justo.');
insert into contact (id, phone_number, email, profile_link) values (79, '498-676-2953', 'rwitson26@merriam-webster.com', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into contact (id, phone_number, email, profile_link) values (80, '364-622-8291', 'jlammers27@scientificamerican.com', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into contact (id, phone_number, email, profile_link) values (81, '608-182-3807', 'aspeere28@imgur.com', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into contact (id, phone_number, email, profile_link) values (82, '708-718-7020', 'azarb29@umich.edu', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.');
insert into contact (id, phone_number, email, profile_link) values (83, '302-960-0795', 'whooke2a@moonfruit.com', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into contact (id, phone_number, email, profile_link) values (84, '359-901-0150', 'posirin2b@omniture.com', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into contact (id, phone_number, email, profile_link) values (85, '318-180-4058', 'gvolkers2c@topsy.com', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.');
insert into contact (id, phone_number, email, profile_link) values (86, '914-160-7149', 'xmartinets2d@tiny.cc', 'Vivamus tortor.');
insert into contact (id, phone_number, email, profile_link) values (87, '340-572-0592', 'dpeakman2e@patch.com', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into contact (id, phone_number, email, profile_link) values (88, '298-465-4685', 'nbiers2f@artisteer.com', 'In quis justo. Maecenas rhoncus aliquam lacus.');
insert into contact (id, phone_number, email, profile_link) values (89, '948-879-5917', 'dbrockbank2g@mediafire.com', 'Vestibulum sed magna at nunc commodo placerat.');
insert into contact (id, phone_number, email, profile_link) values (90, '760-573-4498', 'ceager2h@theglobeandmail.com', 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into contact (id, phone_number, email, profile_link) values (91, '401-628-7095', 'mvanvuuren2i@usatoday.com', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.');
insert into contact (id, phone_number, email, profile_link) values (92, '887-436-0425', 'gstorry2j@4shared.com', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into contact (id, phone_number, email, profile_link) values (93, '567-755-7702', 'sdealy2k@home.pl', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into contact (id, phone_number, email, profile_link) values (94, '535-941-4139', 'preaper2l@mashable.com', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into contact (id, phone_number, email, profile_link) values (95, '573-433-6151', 'cdods2m@europa.eu', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into contact (id, phone_number, email, profile_link) values (96, '582-492-7141', 'jtrue2n@weibo.com', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into contact (id, phone_number, email, profile_link) values (97, '938-273-8430', 'sendon2o@cafepress.com', 'Fusce consequat. Nulla nisl. Nunc nisl.');
insert into contact (id, phone_number, email, profile_link) values (98, '206-887-4460', 'sgonsalvo2p@lycos.com', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into contact (id, phone_number, email, profile_link) values (99, '856-909-6214', 'cwillimot2q@blog.com', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.');
insert into contact (id, phone_number, email, profile_link) values (100, '794-149-8994', 'wkimmings2r@sohu.com', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');

--illness
    --illness marking
        --heaviness L-light, M-moderate, S-severe, E-extremely severe, T-terminal

insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (1, 2, '6734', 'L', '2021-10-27 11:27:42', '2022-04-29');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (2, 3, '8886', 'E', '2022-05-25 01:59:39', '2022-01-24');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (3, 4, '9612', 'E', '2022-07-15 09:50:42', '2022-02-12');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (4, 5, '2039', 'M', '2022-09-26 18:32:22', '2022-02-04');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (5, 6, '1989', 'L', '2022-03-21 16:59:22', '2022-08-15');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (6, 7, '2880', 'E', '2022-02-02 09:33:28', '2021-12-31');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (7, 8, '6318', 'E', '2022-01-09 21:49:02', '2022-07-04');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (8, 9, '0884', 'S', '2022-07-06 18:23:12', '2021-11-12');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (9, 10, '0491', 'M', '2022-01-27 12:44:46', '2021-12-07');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (10, 11, '4159', 'S', '2022-05-02 06:55:32', '2022-03-26');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (11, 12, '8682', 'L', '2022-02-12 06:28:53', '2022-01-31');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (12, 13, '0882', 'M', '2022-04-30 08:41:12', '2022-05-25');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (13, 14, '4219', 'E', '2022-09-25 16:28:28', '2022-05-22');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (14, 15, '6947', 'S', '2022-05-13 03:24:21', '2022-07-16');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (15, 16, '1550', 'L', '2021-12-03 11:02:05', '2022-05-15');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (16, 17, '5553', 'E', '2022-08-05 07:27:15', '2022-02-22');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (17, 18, '7381', 'L', '2022-07-21 01:54:55', '2022-04-19');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (18, 19, '5385', 'M', '2022-06-01 10:46:39', '2021-11-24');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (19, 20, '3403', 'L', '2022-08-16 00:15:46', '2022-04-19');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (20, 21, '9627', 'M', '2022-09-28 04:08:51', '2022-05-22');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (21, 22, '5757', 'L', '2022-10-23 15:22:57', '2022-01-17');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (22, 23, '7229', 'M', '2022-07-27 10:40:27', '2022-02-09');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (23, 24, '9128', 'L', '2022-02-17 15:35:40', '2022-04-15');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (24, 25, '2224', 'T', '2022-05-30 23:07:28', '2022-07-31');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (25, 26, '9346', 'S', '2022-01-19 05:12:18', '2022-06-10');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (26, 27, '5153', 'S', '2022-07-02 18:47:12', '2022-03-18');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (27, 28, '6475', 'L', '2022-04-25 19:39:42', '2022-01-10');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (28, 29, '6883', 'L', '2022-03-22 17:38:49', '2021-11-12');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (29, 30, '2785', 'S', '2022-08-26 19:28:34', '2022-06-02');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (30, 31, '2565', 'M', '2022-06-13 20:25:26', '2022-09-01');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (31, 32, '5504', 'T', '2022-04-18 16:04:22', '2022-06-11');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (32, 33, '4234', 'E', '2022-06-20 00:26:52', '2022-09-15');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (33, 34, '5210', 'M', '2022-04-10 01:33:03', '2021-12-07');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (34, 35, '1819', 'T', '2022-06-22 10:54:44', '2022-07-27');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (35, 36, '4433', 'L', '2021-11-23 09:01:59', '2022-10-20');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (36, 37, '4958', 'M', '2022-06-12 03:19:04', '2022-07-23');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (37, 38, '5294', 'M', '2022-02-20 03:41:31', '2021-12-01');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (38, 39, '6239', 'S', '2022-02-28 23:28:28', '2021-11-14');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (39, 40, '9358', 'L', '2022-01-17 15:50:38', '2021-12-15');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (40, 41, '1749', 'M', '2022-08-12 09:32:36', '2022-02-14');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (41, 42, '8131', 'T', '2021-12-26 12:39:52', '2022-06-10');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (42, 43, '7223', 'L', '2022-05-20 16:03:27', '2021-11-14');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (43, 44, '9178', 'T', '2022-10-01 19:24:10', '2022-02-05');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (44, 45, '0971', 'L', '2022-07-16 07:11:11', '2021-12-09');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (45, 46, '5280', 'E', '2022-04-27 10:55:33', '2021-11-24');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (46, 47, '0270', 'M', '2022-08-13 19:13:22', '2022-08-24');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (47, 48, '4816', 'M', '2022-07-04 04:53:52', '2022-02-26');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (48, 49, '6604', 'T', '2021-12-23 00:45:20', '2022-02-23');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (49, 50, '6388', 'S', '2021-11-07 19:24:31', '2022-09-02');
insert into illness (id, medical_card_id, type_id, heaviness, appearance_dttm, recovery_dt) values (50, 51, '3096', 'T', '2021-12-04 13:00:26', '2022-06-22');

--person_data

insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (1, 'Axtell', 'Pepita', '1987-09-25', null, 'F', 1, 1, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (2, 'Ludovico', 'Henrieta', '1982-01-07', null, 'F', 2, 2, 1);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (3, 'Bogays', 'Chrissy', '1999-08-10', null, 'F', 3, 3, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (4, 'Dallemore', 'Stanford', '1995-10-07', null, 'M', 4, 4, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (5, 'Luckie', 'Tobie', '1975-02-22', null, 'M', 5, 5, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (6, 'Boldero', 'Roze', '1978-03-29', null, 'F', 6, 6, 3);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (7, 'Matyashev', 'Giralda', '1995-04-06', null, 'F', 7, 7, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (8, 'Brixey', 'Ari', '1987-03-30', null, 'M', 8, 8, 4);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (9, 'Carlisle', 'Ellen', '2000-02-03', null, 'F', 9, 9, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (10, 'Brownlow', 'Rowan', '1983-06-27', null, 'M', 10, 10, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (11, 'Combes', 'Collie', '1995-06-04', null, 'F', 11, 11, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (12, 'Elger', 'Daphna', '1975-07-03', null, 'F', 12, 12, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (13, 'Youthead', 'Brittany', '1999-10-01', null, 'F', 13, 13, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (14, 'Bungey', 'Cleveland', '1989-04-20', null, 'M', 14, 14, 7);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (15, 'Playhill', 'Naomi', '1971-08-28', null, 'F', 15, 15, 7);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (16, 'Wanne', 'Belia', '1976-03-29', null, 'F', 16, 16, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (17, 'Espadater', 'Chrystal', '1978-03-14', null, 'F', 17, 17, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (18, 'Maliphant', 'Chloe', '1992-03-13', null, 'F', 18, 18, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (19, 'Sherwood', 'Jerrilyn', '2001-08-31', null, 'F', 19, 19, 9);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (20, 'Garbutt', 'Pier', '1983-05-30', null, 'F', 20, 20, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (21, 'Dowsett', 'Conant', '1982-01-19', null, 'M', 21, 21, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (22, 'Devorill', 'Yorgo', '1983-11-09', null, 'M', 22, 22, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (23, 'Enstone', 'Gabriella', '1985-06-29', null, 'F', 23, 23, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (24, 'Statersfield', 'Lind', '1994-03-13', null, 'F', 24, 24, 12);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (25, 'Sibson', 'Abey', '1974-08-09', null, 'M', 25, 25, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (26, 'Clelle', 'Jeni', '2001-07-01', null, 'F', 26, 26, 13);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (27, 'Darby', 'Massimo', '1991-02-15', null, 'M', 27, 27, 13);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (28, 'Phillip', 'Almeda', '2000-04-09', null, 'F', 28, 28, 14);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (29, 'Torrans', 'Sella', '1991-03-11', null, 'F', 29, 29, 14);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (30, 'Garnham', 'Nicholle', '1980-05-14', null, 'F', 30, 30, 15);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (31, 'Dredge', 'Levy', '1989-11-25', null, 'M', 31, 31, 15);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (32, 'Figgures', 'Wiatt', '1975-11-13', null, 'M', 32, 32, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (33, 'Itzkovich', 'Judie', '1981-06-25', null, 'F', 33, 33, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (34, 'Laffling', 'Charles', '1976-11-10', null, 'M', 34, 34, 17);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (35, 'Gosnoll', 'Bevin', '1981-10-25', null, 'M', 35, 35, 17);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (36, 'Senussi', 'Jozef', '1999-07-09', null, 'M', 36, 36, 18);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (37, 'Bwye', 'Allen', '1992-06-21', null, 'M', 37, 37, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (38, 'Moret', 'Brucie', '1992-01-27', null, 'M', 38, 38, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (39, 'Frankel', 'Freddy', '1995-10-11', null, 'M', 39, 39, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (40, 'Farres', 'Bettina', '1981-07-24', null, 'F', 40, 40, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (41, 'McVitie', 'Orelia', '1986-10-12', null, 'F', 41, 41, 20);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (42, 'Reynault', 'Arlan', '1981-10-17', null, 'M', 42, 42, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (43, 'Giannasi', 'Cassie', '1988-06-24', null, 'F', 43, 43, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (44, 'Abendroth', 'Marylee', '2000-09-25', null, 'F', 44, 44, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (45, 'Janc', 'Bealle', '1971-11-15', null, 'M', 45, 45, 22);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (46, 'Gallacher', 'Aila', '2000-11-13', null, 'F', 46, 46, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (47, 'Corp', 'Yevette', '1981-03-11', null, 'F', 47, 47, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (48, 'Albrecht', 'Collen', '1991-07-03', null, 'F', 48, 48, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (49, 'Bartolini', 'Rosemarie', '1979-06-25', null, 'F', 49, 49, 24);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (50, 'Archard', 'Arin', '1999-02-06', null, 'M', 50, 50, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (51, 'Chastelain', 'Glenden', '1979-10-01', null, 'M', 51, 51, 25);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (52, 'Winnard', 'Vonny', '1978-01-09', null, 'F', 52, 52, 26);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (53, 'Trengove', 'Danita', '1988-11-10', null, 'F', 53, 53, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (54, 'Cleevely', 'Rudolfo', '1995-07-03', null, 'M', 54, 54, 27);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (55, 'Prier', 'Sarina', '1980-09-22', null, 'F', 55, 55, 27);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (56, 'Fielden', 'Kora', '1987-02-18', null, 'F', 56, 56, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (57, 'Daile', 'Danie', '1978-11-01', null, 'M', 57, 57, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (58, 'Vesty', 'Dalt', '1971-12-02', null, 'M', 58, 58, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (59, 'Eneas', 'Brice', '1998-12-06', null, 'M', 59, 59, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (60, 'Tangye', 'Misty', '1978-10-12', null, 'F', 60, 60, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (61, 'Rizzetti', 'Hobey', '1971-04-21', null, 'M', 61, 61, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (62, 'Ceaser', 'Honey', '1990-09-23', null, 'F', 62, 62, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (63, 'Dulen', 'Kissiah', '1996-07-01', null, 'F', 63, 63, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (64, 'Guthrie', 'Emmit', '1995-09-08', null, 'M', 64, 64, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (65, 'Fadell', 'Aileen', '1989-11-13', null, 'F', 65, 65, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (66, 'Lilbourne', 'Nils', '1999-10-12', null, 'M', 66, 66, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (67, 'Pittendreigh', 'Chickie', '1975-07-20', null, 'M', 67, 67, 33);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (68, 'Masser', 'Humberto', '1971-05-27', null, 'M', 68, 68, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (69, 'Keasey', 'Kelcey', '1974-09-16', null, 'F', 69, 69, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (70, 'Cowsby', 'Karon', '1971-10-16', null, 'F', 70, 70, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (71, 'Stockford', 'Slade', '1971-09-24', null, 'M', 71, 71, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (72, 'Mougeot', 'Laurens', '1987-07-04', null, 'M', 72, 72, 36);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (73, 'De Francisci', 'Bee', '1977-08-08', null, 'F', 73, 73, 36);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (74, 'Bleyman', 'Ahmad', '1990-06-29', null, 'M', 74, 74, 37);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (75, 'Pighills', 'Rubie', '1973-12-13', null, 'F', 75, 75, 37);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (76, 'Orrey', 'Mano', '1973-09-28', null, 'M', 76, 76, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (77, 'Galway', 'Jaye', '2002-09-25', null, 'M', 77, 77, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (78, 'Ashworth', 'Nevile', '1971-07-04', null, 'M', 78, 78, 39);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (79, 'Merwe', 'Janka', '1974-04-18', null, 'F', 79, 79, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (80, 'Lotterington', 'Jacquette', '1984-04-19', null, 'F', 80, 80, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (81, 'Gunther', 'Erl', '1997-02-12', null, 'M', 81, 81, 40);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (82, 'Filpi', 'Tandi', '1973-07-25', null, 'F', 82, 82, 41);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (83, 'Iddy', 'Shanon', '2001-10-31', null, 'F', 83, 83, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (84, 'Blackboro', 'Adams', '1995-01-26', null, 'M', 84, 84, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (85, 'Bowe', 'Marlin', '1999-04-13', null, 'M', 85, 85, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (86, 'Burker', 'Tamiko', '1972-11-11', null, 'F', 86, 86, 43);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (87, 'Coneron', 'Kiley', '1985-05-17', null, 'M', 87, 87, 43);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (88, 'D''Arrigo', 'Estevan', '1976-03-31', null, 'M', 88, 88, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (89, 'Kernocke', 'Tannie', '1973-03-20', null, 'M', 89, 89, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (90, 'Heustice', 'Colette', '1999-04-07', null, 'F', 90, 90, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (91, 'Vanner', 'Kayne', '1997-10-02', null, 'M', 91, 91, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (92, 'Sonnenschein', 'Hartwell', '1983-01-20', null, 'M', 92, 92, 46);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (93, 'Athey', 'Edgard', '2001-01-26', null, 'M', 93, 93, 46);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (94, 'Sutor', 'Gerianna', '1995-03-21', null, 'F', 94, 94, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (95, 'Golland', 'Genna', '1983-07-24', null, 'F', 95, 95, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (96, 'Duffrie', 'Elbertina', '1970-11-29', null, 'F', 96, 96, 48);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (97, 'Elliker', 'Angela', '1991-09-22', null, 'F', 97, 97, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (98, 'Rousby', 'Leila', '1991-11-19', null, 'F', 98, 98, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (99, 'Glen', 'Shanan', '1996-11-03', null, 'M', 99, 99, null);
insert into person_data (id, last_name, first_name, birth_dt, age, sex, contact_id, medical_card_id, parent_id) values (100, 'Browse', 'Stephana', '1986-09-25', null, 'F', 100, 100, 50);

--address

insert into address (id, contact_id, country_id, city, index, street, building, flat) values (1, 1, '39', 'Mayhan', '52639', 'Mcguire', 'Trail', '957');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (2, 2, '01', 'Santa Marta', '70508', 'Loomis', 'Point', '105');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (3, 3, '09', 'Río Guayabal de Yateras', '38429', 'Erie', 'Drive', '984');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (4, 4, '76', 'Göteborg', '05999', 'Kings', 'Trail', '390');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (5, 5, '15', 'Sembung', '29951', 'Cody', 'Crossing', '068');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (6, 6, '19', 'Yongning', '23291', 'Forest Run', 'Alley', '816');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (7, 7, '45', 'Kroya', '81173', 'Northport', 'Center', '213');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (8, 8, '66', 'Kushnarënkovo', '08171', 'Bunting', 'Crossing', '116');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (9, 9, '55', 'Muncar', '78751', 'Novick', 'Circle', '241');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (10, 10, '91', 'Río de Jesús', '14643', 'Veith', 'Park', '828');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (11, 11, '17', 'Sehwān', '28109', 'Talisman', 'Junction', '560');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (12, 12, '39', 'Lugovskoy', '69568', 'Dennis', 'Plaza', '257');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (13, 13, '10', 'Černošice', '18922', 'Golf View', 'Terrace', '474');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (14, 14, '72', 'Lis', '15870', 'Linden', 'Parkway', '821');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (15, 15, '24', 'Luocun', '71507', 'Helena', 'Drive', '595');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (16, 16, '98', 'Santa Ana', '68438', 'Waxwing', 'Court', '013');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (17, 17, '10', 'Siheyuan', '36002', 'Village', 'Parkway', '196');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (18, 18, '81', 'Taluncemara', '05232', 'Jenifer', 'Pass', '916');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (19, 19, '62', 'Heyou', '19334', 'Shoshone', 'Alley', '009');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (20, 20, '80', 'Nagykanizsa', '38704', 'Kingsford', 'Drive', '324');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (21, 21, '39', 'Sagara', '83386', 'Butternut', 'Center', '847');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (22, 22, '18', 'Wanglu Kulon', '16765', 'Bay', 'Place', '797');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (23, 23, '25', 'Limonade', '29503', 'Shasta', 'Crossing', '288');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (24, 24, '03', 'Daping', '66007', 'Longview', 'Alley', '716');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (25, 25, '16', 'Al Hadā', '27201', 'Red Cloud', 'Court', '781');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (26, 26, '76', 'Pinar del Río', '46030', 'Shoshone', 'Court', '112');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (27, 27, '66', 'Maglaj', '48701', 'Bartelt', 'Place', '455');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (28, 28, '43', 'Naghalin', '95219', 'Dorton', 'Parkway', '236');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (29, 29, '86', 'Espumoso', '78752', 'Reindahl', 'Plaza', '330');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (30, 30, '84', 'Popovi', '74104', 'Bluestem', 'Avenue', '993');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (31, 31, '53', 'Alto Río Senguer', '21570', 'Messerschmidt', 'Terrace', '627');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (32, 32, '68', 'Świętajno', '85867', 'Sunfield', 'Drive', '722');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (33, 33, '97', 'Kubangwaru', '48476', 'Derek', 'Place', '523');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (34, 34, '87', 'Il’inskiy Pogost', '21539', 'North', 'Terrace', '121');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (35, 35, '71', 'Chaihu', '62321', 'Westerfield', 'Plaza', '478');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (36, 36, '73', 'Zagórów', '41040', 'Sloan', 'Lane', '404');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (37, 37, '31', 'Shchastya', '12598', 'Granby', 'Parkway', '689');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (38, 38, '61', 'Kuala Lumpur', '39340', 'Harbort', 'Junction', '074');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (39, 39, '18', 'San Fernando', '12194', 'Merry', 'Hill', '766');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (40, 40, '61', 'Dongshi', '65068', 'Morning', 'Way', '076');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (41, 41, '90', 'Caotang', '34070', 'Bartelt', 'Pass', '448');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (42, 42, '99', 'Saint-Brieuc', '43444', 'Towne', 'Alley', '174');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (43, 43, '65', 'Murcia', '77094', 'Carey', 'Alley', '911');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (44, 44, '70', 'Santa Fe', '61564', '6th', 'Pass', '760');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (45, 45, '71', 'Hulín', '75090', 'Sachtjen', 'Trail', '712');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (46, 46, '90', 'Weifang', '64281', 'Carpenter', 'Circle', '047');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (47, 47, '70', 'Kāshmar', '51208', 'Nancy', 'Plaza', '105');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (48, 48, '97', 'Drammen', '36183', 'Lyons', 'Parkway', '010');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (49, 49, '99', 'Tangjian', '18030', 'Steensland', 'Hill', '037');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (50, 50, '34', 'Resplendor', '04500', 'Briar Crest', 'Circle', '560');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (51, 51, '79', 'Borgarnes', '53583', 'Merrick', 'Road', '258');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (52, 52, '79', 'Černošín', '03980', 'Warbler', 'Place', '984');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (53, 53, '00', 'Maguling', '39301', 'Nelson', 'Road', '258');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (54, 54, '25', 'Vide', '34803', 'Thompson', 'Plaza', '353');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (55, 55, '33', 'Bishan', '16316', 'Miller', 'Avenue', '761');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (56, 56, '92', 'Ballina', '42060', 'Graedel', 'Pass', '528');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (57, 57, '77', 'Gambarjati', '40477', 'Portage', 'Alley', '600');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (58, 58, '45', 'Lille', '11348', 'Westerfield', 'Alley', '543');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (59, 59, '71', 'Zhouxi', '05106', 'Beilfuss', 'Pass', '968');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (60, 60, '06', 'Norrtälje', '81972', 'Maple Wood', 'Pass', '039');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (61, 61, '91', 'Tocoa', '18260', 'Mallard', 'Center', '897');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (62, 62, '26', 'Arazane', '10628', 'Truax', 'Crossing', '800');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (63, 63, '44', 'Příbram', '95397', 'Reinke', 'Way', '630');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (64, 64, '76', 'Arteni', '56796', 'Milwaukee', 'Avenue', '737');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (65, 65, '55', 'Colombo', '06229', 'Northfield', 'Crossing', '743');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (66, 66, '12', 'Ojrzeń', '45054', 'Doe Crossing', 'Hill', '854');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (67, 67, '15', 'Chornyanka', '12757', 'Bayside', 'Alley', '939');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (68, 68, '66', 'Arujá', '53132', 'Becker', 'Parkway', '276');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (69, 69, '36', 'Bang Kaeo', '02613', 'Fremont', 'Hill', '272');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (70, 70, '41', 'Cantapoy', '78455', 'Acker', 'Circle', '617');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (71, 71, '11', 'Nanyi', '08409', 'Londonderry', 'Place', '411');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (72, 72, '33', 'Duwakkandung', '07547', 'Weeping Birch', 'Lane', '834');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (73, 73, '07', 'Jistebník', '65237', 'Westend', 'Pass', '623');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (74, 74, '82', 'Uhlove', '48586', 'Glacier Hill', 'Alley', '105');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (75, 75, '40', 'Dankalwa', '30242', 'Westend', 'Plaza', '564');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (76, 76, '52', 'Lebedyan’', '36269', 'Delladonna', 'Alley', '882');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (77, 77, '35', 'Songqiao', '05945', 'Johnson', 'Lane', '025');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (78, 78, '19', 'Indianapolis', '73775', 'Beilfuss', 'Court', '239');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (79, 79, '13', 'Ban Mai', '91088', 'Kinsman', 'Parkway', '646');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (80, 80, '72', 'Jiamaogong', '48187', 'Darwin', 'Center', '813');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (81, 81, '72', 'Sumberkemuning', '82394', 'Laurel', 'Alley', '656');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (82, 82, '16', 'Kijini', '01422', 'Maple', 'Court', '671');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (83, 83, '09', 'San Isidro', '84120', 'Dovetail', 'Court', '295');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (84, 84, '15', 'Sukadami', '35610', 'Badeau', 'Pass', '944');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (85, 85, '91', 'Yumani', '48412', 'Lakewood', 'Center', '912');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (86, 86, '73', 'Bakaran Kulon', '58681', 'Judy', 'Crossing', '662');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (87, 87, '51', 'Xindi', '30752', 'Thierer', 'Street', '984');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (88, 88, '12', 'Talakag', '89633', 'Hanson', 'Trail', '344');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (89, 89, '71', 'Lijiapu', '43254', 'Butterfield', 'Place', '748');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (90, 90, '30', 'Centar Župa', '36908', 'Graedel', 'Terrace', '853');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (91, 91, '29', 'Spuž', '16750', 'Bluejay', 'Trail', '796');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (92, 92, '48', 'Limulan', '14654', 'Bowman', 'Pass', '158');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (93, 93, '96', 'Slobodka', '39004', 'Forest Dale', 'Junction', '016');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (94, 94, '79', 'Sainte-Anne-des-Monts', '82663', 'Alpine', 'Drive', '106');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (95, 95, '59', 'Hispania', '63266', 'Katie', 'Center', '349');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (96, 96, '29', 'Dobrošte', '32534', 'Everett', 'Plaza', '503');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (97, 97, '38', 'Ferreñafe', '41916', 'Carpenter', 'Place', '470');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (98, 98, '14', 'Kap Choeng', '46864', 'Toban', 'Place', '146');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (99, 99, '61', 'Bobon', '06636', 'Farwell', 'Point', '031');
insert into address (id, contact_id, country_id, city, index, street, building, flat) values (100, 100, '16', 'Kadugede', '76471', 'Hauk', 'Junction', '183');
