server:
  port: 8091
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      # ????????? ????-???? ?????????? = 2???
      connection-timeout: 120000
      max-lifetime: 120000
      minimum-idle: 4
#      validation-timeout: 120000

management:
  endpoints:
    web:
      exposure:
        include: "*"
